window.PAS_QUESTIONS=[
['Ley 20.091 / SSN','Una aseguradora pierde el 30% de su capital mínimo. ¿Cuál es la consecuencia que mejor coincide con el material?',['La revocación automática de la autorización para operar','La obligación de abstenerse de celebrar nuevos contratos en todas o algunas ramas hasta recomponer el capital','La liquidación forzosa inmediata, sin posibilidad de regularización','La prohibición exclusiva de distribuir dividendos, pudiendo seguir emitiendo normalmente'],1,'El material vincula la pérdida del 30% del capital mínimo con una medida severa de regularización: la SSN puede ordenar abstenerse de celebrar nuevos contratos hasta alcanzar nuevamente el capital mínimo.'],
['Ley 20.091 / SSN','Respecto de las inversiones de las aseguradoras, ¿qué afirmación es más precisa según el material?',['Deben estar íntegramente en títulos públicos nacionales','Como regla deben estar radicadas en Argentina, aunque existen excepciones expresamente autorizadas','Pueden radicarse libremente en cualquier país si la entidad conserva solvencia','Solo las inversiones vinculadas a Vida deben radicarse en Argentina'],1,'El régimen estudiado establece la radicación en Argentina como regla, con excepciones específicas autorizadas por la autoridad de control.'],
['Ley 20.091 / SSN','¿Cuál de las siguientes situaciones describe mejor la finalidad del Plan de Regularización y Saneamiento?',['Maximizar la rentabilidad de la cartera de inversiones aun a costa de reducir liquidez','Superar una situación deficitaria procurando al mismo tiempo proteger a asegurados, beneficiarios y damnificados','Sustituir todas las reservas técnicas por aportes de capital','Permitir que la entidad continúe operando sin restricciones hasta el cierre del ejercicio'],1,'El plan busca recomponer la situación patrimonial y técnica sin perder de vista la tutela de asegurados, beneficiarios y damnificados.'],
['Ley 20.091 / SSN','Una inversión incumple las normas internas observadas por la SSN y el plan de regularización no se cumple. ¿Qué consecuencia señala el material?',['La inversión deja de ser computable para acreditar las relaciones técnicas, sin perjuicio de sanciones','La inversión se transforma automáticamente en reserva legal','La SSN debe adquirir el activo a valor de mercado','La entidad puede mantenerla computable si tiene resultado positivo'],0,'El material indica que, si el plan es rechazado o incumplido, las inversiones observadas no serán computables para acreditar las relaciones técnicas exigidas.'],

['PAS / Ley 22.400','Un PAS interviene en una póliza cuya prima se paga en cuotas. ¿Cuándo adquiere su derecho a comisión?',['Al emitirse la póliza por el total de la prima anual','Cuando la aseguradora percibe efectivamente cada cuota, en forma proporcional','Cuando el asegurado firma la propuesta, aunque luego no pague','Al vencer cada cuota, aunque no haya sido abonada'],1,'El art. 6 estudiado vincula el derecho a comisión con la percepción efectiva de la prima; en seguros en cuotas, proporcionalmente a cada cuota percibida.'],
['PAS / Ley 22.400','Un cliente entrega un cheque al PAS para pagar una póliza. A efectos del derecho a comisión, ¿qué criterio recoge el material?',['La sola entrega del cheque equivale siempre a pago efectivo','El cheque se considera pago efectivo solo cuando es cancelado','El cheque nunca puede utilizarse para el pago de primas','El derecho a comisión nace con la recepción física del cheque por el PAS'],1,'El material aclara que cheques, pagarés u otras promesas u órdenes de pago no se consideran pago efectivo hasta su cancelación.'],
['PAS / Ley 22.400','Un productor decide suspender voluntariamente su matrícula por razones justificadas. Durante la suspensión:',['Puede intermediar si no cobra comisión','No puede ejercer la actividad propia de intermediación y queda liberado de capacitación continuada mientras dure la suspensión','Puede operar únicamente con seguros patrimoniales','Debe rendir nuevamente el examen para reactivar la matrícula en todos los casos'],1,'El régimen citado impide ejercer la actividad durante la suspensión y libera al PAS de los cursos de capacitación continuada mientras ésta se mantenga.'],
['PAS / Ley 22.400','Una persona no matriculada consigue una póliza para un cliente y pretende cobrar una parte de la comisión. ¿Qué solución se ajusta mejor al material?',['Puede cobrar si la aseguradora lo autoriza por escrito','No tiene derecho a comisión ni remuneración por la concertación y la aseguradora debe abstenerse de operar con ella','Puede cobrar hasta un porcentaje menor al del PAS matriculado','Puede cobrar si la operación fue supervisada por un PAS'],1,'El art. 7 estudiado prohíbe pagar comisiones o retribuciones por concertación a personas no inscriptas.'],

['Contrato / Ley 17.418','Un asegurador descubre una reticencia relevante ocho meses después de emitida la póliza. ¿Desde cuándo corre el plazo de tres meses para impugnar el contrato según el material?',['Desde la fecha de emisión','Desde el inicio de vigencia','Desde que el asegurador conoce la reticencia o falsedad','Desde la fecha del eventual siniestro'],2,'El material reproduce que el asegurador debe impugnar el contrato dentro de los tres meses de haber conocido la reticencia o falsedad.'],
['Contrato / Ley 17.418','¿Cuál de estas situaciones configura mejor una reticencia relevante?',['Omitir un dato que no influye en la aceptación ni en las condiciones del riesgo','Omitir una circunstancia conocida que, de haber sido informada, habría impedido el contrato o modificado sus condiciones','No informar un hecho ocurrido después de extinguido el contrato','No recordar el número de póliza al denunciar un siniestro'],1,'La relevancia de la reticencia se mide por su aptitud para haber impedido la contratación o modificado sus condiciones.'],
['Contrato / Ley 17.418','Un bien vale $1.000.000 y está asegurado por $600.000 bajo una cobertura a prorrata. El daño es de $250.000. ¿Cuál es la indemnización antes de franquicias?',['$150.000','$250.000','$600.000','$100.000'],0,'La relación asegurada es 60%. A prorrata: $250.000 × 60% = $150.000.'],
['Contrato / Ley 17.418','El mismo bien de $1.000.000 está asegurado por $600.000, pero la cobertura es a Primer Riesgo Absoluto. El daño asciende a $250.000. ¿Qué corresponde antes de franquicias?',['$150.000','$250.000','$600.000','$100.000'],1,'En Primer Riesgo Absoluto no se aplica la regla proporcional por infraseguro; se indemniza el daño hasta el límite de la suma asegurada.'],

['Siniestros','El asegurador recibe toda la información necesaria para pronunciarse y guarda silencio más allá del plazo legal estudiado. ¿Cuál es el efecto central?',['El siniestro se considera rechazado por falta de respuesta','Opera la aceptación del derecho del asegurado','Se suspende la cobertura de la póliza','El plazo se reinicia automáticamente por otros 30 días'],1,'El material estudia el silencio del asegurador como aceptación cuando transcurre el plazo legal sin pronunciamiento.'],
['Siniestros','Durante un incendio, el asegurado permite romper una pared para evitar la propagación del fuego. ¿Cómo se vincula esto con sus cargas?',['Constituye incumplimiento porque debe conservar intactos los bienes','Es coherente con la carga de salvamento si la medida es razonable para evitar o disminuir el daño','Solo es válido si existe orden judicial','Se considera abandono de los restos'],1,'La carga de salvamento exige adoptar medidas razonables para evitar o disminuir el daño.'],
['Siniestros','Un asegurado proporciona datos falsos que generan gastos extraordinarios de verificación. ¿Qué matiz es correcto respecto de los gastos de liquidación?',['Todos los gastos son siempre del asegurador sin excepción','Los gastos necesarios son del asegurador, salvo los provocados por indicaciones falsas del asegurado','Todos los gastos pasan a cargo del PAS','Los gastos se dividen necesariamente por mitades'],1,'El material atribuye al asegurador los gastos necesarios de verificación y liquidación, exceptuando los derivados de indicaciones falsas.'],
['Siniestros','¿Qué requisito formal se destaca para un rechazo de siniestro?',['Debe ser verbal para conservar flexibilidad','Debe notificarse fehacientemente y contener fundamentos claros','Solo debe asentarse en el registro interno de la compañía','Basta con comunicarlo al PAS sin informar al asegurado'],1,'El rechazo debe notificarse de manera fehaciente y fundarse claramente.'],

['ART / Ley 24.557','Un trabajador tiene una disminución permanente de su capacidad laborativa del 66%. ¿Cómo clasifica la LRT esa incapacidad?',['ILP parcial, porque la total exige superar el 66%','ILP total, porque es total cuando la disminución es igual o superior al 66%','ILT, porque toda incapacidad comienza como temporaria','Gran invalidez automáticamente'],1,'La LRT considera total la ILP cuando la disminución permanente es igual o superior al 66%; es parcial cuando es inferior.'],
['ART / Ley 24.557','¿Cuál de estas combinaciones describe correctamente el cese de la Incapacidad Laboral Temporaria?',['Alta médica, declaración de ILP, transcurso del plazo legal o muerte','Solo alta médica o renuncia del trabajador','Alta médica, despido o cambio de ART','Solo declaración de ILP o jubilación'],0,'La norma estudiada contempla alta médica, declaración de ILP, transcurso de dos años desde la primera manifestación invalidante y muerte.'],
['ART / Ley 24.557','En una ILT, ¿quién soporta el pago durante los primeros diez días y quién desde el día undécimo según el material?',['ART desde el primer día; empleador desde el día 11','Empleador los primeros 10 días; ART desde el día 11','Obra social los primeros 10 días; ART desde el día 11','Empleador durante toda la ILT'],1,'El módulo indica que los primeros diez días están a cargo del empleador y, desde el día undécimo, a cargo de la ART.'],
['ART / Ley 24.557','¿Cuál de las siguientes NO es una prestación en especie enumerada por la LRT?',['Recalificación profesional','Prótesis y ortopedia','Rehabilitación','Indemnización dineraria por ILP'],3,'Las prestaciones en especie incluyen asistencia médica y farmacéutica, prótesis y ortopedia, rehabilitación, recalificación profesional y servicio funerario.'],

['Vida','En el Seguro Colectivo de Vida Obligatorio del Decreto 1567/74, ¿cuál es la afirmación correcta según el material?',['El suicidio solo se cubre luego de tres años','Cubre muerte por cualquier causa e incluye suicidio sin limitaciones','Solo cubre muerte accidental','El suicidio se cubre únicamente si existe diagnóstico psiquiátrico previo'],1,'El módulo señala que el Seguro Colectivo de Vida Obligatorio cubre muerte por cualquier causa e incluye suicidio sin limitaciones.'],
['Vida','Un trabajador tiene dos empleadores, ambos alcanzados por el Seguro Colectivo de Vida Obligatorio. Si fallece:',['La prestación se duplica porque existen dos relaciones laborales','La prestación se percibe una sola vez','Se paga una prestación por cada empleador pero al 50%','Solo responde el empleador con mayor antigüedad'],1,'El material indica que el trabajador con más de un empleador recibe la prestación una sola vez.'],
['Vida','En materia de reticencia en Vida, el material destaca que para arribar a la nulidad del contrato:',['Toda omisión irrelevante basta','La reticencia debe revestir carácter doloso, por ejemplo omitir una enfermedad preexistente conocida','Debe existir siempre un siniestro dentro de los 30 días','Solo importa la edad declarada'],1,'El módulo de Vida señala especialmente la reticencia dolosa como supuesto que puede conducir a la nulidad.'],
['Vida','Si no existe designación eficaz de beneficiarios en el Seguro Colectivo de Vida Obligatorio, el material remite a:',['La decisión discrecional de la aseguradora','Las reglas de derechohabientes previstas por la normativa previsional mencionada','El PAS interviniente','Los herederos testamentarios exclusivamente'],1,'El material remite a las reglas de derechohabientes y a la acreditación mediante ANSES o caja previsional cuando la designación falta o resulta ineficaz.'],

['Automotores','Un vehículo participa en una prueba de velocidad y sufre un siniestro. ¿Cuál es la opción más precisa?',['La RC siempre responde porque el daño a terceros nunca admite exclusiones','La participación en certámenes o pruebas de velocidad puede configurar una exclusión de cobertura','Solo se excluyen daños propios, pero nunca la RC','La exclusión solo opera si hubo apuestas'],1,'El material de Automotores contempla como exclusión la participación en certámenes o pruebas de velocidad.'],
['Automotores','¿Qué describe mejor el concepto de franquicia?',['El máximo que pagará la aseguradora','La porción del daño que queda a cargo del asegurado conforme al contrato','El porcentaje de comisión del PAS','La diferencia entre prima pura y premio'],1,'La franquicia es la parte del daño que contractualmente queda a cargo del asegurado.'],
['Automotores','La cobertura básica de Responsabilidad Civil de Automotores se orienta principalmente a:',['Daños materiales del propio vehículo asegurado','Daños causados a terceros dentro del alcance y límites contratados','Desgaste mecánico del vehículo','Robo parcial de accesorios'],1,'La RC protege frente a la responsabilidad por daños a terceros; los daños propios requieren coberturas específicas.'],
['Automotores','El indicador Vehículos Expuestos a Riesgo se construye considerando:',['Solo la cantidad de pólizas emitidas al cierre','Los días de cobertura efectiva de cada vehículo dentro del período analizado','Únicamente los vehículos que tuvieron siniestros','La cantidad de vehículos registrados en el país, estén o no asegurados'],1,'El módulo define el indicador con base en la exposición efectiva medida por días de cobertura dentro del período.'],

['Responsabilidad Civil','En el régimen de RC, el crédito del damnificado sobre la suma asegurada:',['Carece de prioridad frente al asegurado','Tiene privilegio sobre la suma asegurada y sus accesorios, con preferencia sobre el asegurado y sus acreedores','Solo tiene privilegio si el asegurado está en quiebra','Se subordina siempre a los créditos fiscales'],1,'El art. 118 estudiado reconoce privilegio al crédito del damnificado sobre la suma asegurada y accesorios.'],
['Responsabilidad Civil','Si existen varios damnificados y la suma disponible resulta insuficiente, la Ley 17.418 establece que:',['Cobra íntegramente el primero que demande','La indemnización se distribuye a prorrata','El asegurador elige a quién indemnizar primero','Se duplica automáticamente la suma asegurada'],1,'El art. 119 prevé distribución a prorrata cuando existe pluralidad de damnificados.'],
['Responsabilidad Civil','Respecto de la citación en garantía, ¿qué opción coincide con el material?',['Solo puede citar al asegurador el asegurado','El damnificado puede citar en garantía al asegurador hasta que la causa se reciba a prueba','Solo puede citarse al asegurador después de sentencia','La citación en garantía no produce efectos respecto del asegurador'],1,'El art. 118 permite al damnificado citar en garantía al asegurador hasta que se reciba la causa a prueba.'],
['Responsabilidad Civil','La sentencia dictada en el juicio donde el asegurador fue citado en garantía:',['Nunca le resulta oponible','Hace cosa juzgada respecto del asegurador y es ejecutable contra él en la medida del seguro','Es ejecutable sin límite aunque la póliza tenga suma asegurada','Solo obliga al PAS'],1,'La ley dispone que la sentencia hace cosa juzgada respecto del asegurador y es ejecutable contra él en la medida del seguro.'],

['Robo','Una mercadería desaparece sin fuerza en las cosas ni violencia en las personas. Jurídicamente, el hecho se aproxima más a:',['Robo','Hurto','Extorsión','Daño accidental'],1,'El material diferencia hurto de robo por la ausencia de fuerza en las cosas o violencia en las personas.'],
['Robo','En una cobertura de Robo donde se aplica Primer Riesgo Relativo, ¿qué afirmación es más adecuada?',['Es idéntico al Primer Riesgo Absoluto en todos los casos','Puede introducir proporcionalidad según la relación pactada entre suma y valor, a diferencia del Primer Riesgo Absoluto','Siempre exige valor tasado','Nunca admite infraseguro'],1,'El material distingue Primer Riesgo Relativo de Primer Riesgo Absoluto; no deben tratarse como modalidades equivalentes.'],
['Robo','Un bien integrante de un juego sufre robo parcial. Según el material de Robo, la indemnización:',['Incluye siempre la pérdida de valor del juego completo por quedar incompleto','Se limita al perjuicio proporcional de la pieza afectada, sin computar la disminución del valor del conjunto por quedar incompleto','Se paga siempre a valor de reposición de todo el juego','Queda excluida por tratarse de una pieza individual'],1,'El módulo señala que no se toma en cuenta la disminución del valor del juego por quedar incompleto.'],
['Robo','Si un objeto asegurado ya no se fabrica al momento del siniestro, el valor de referencia será:',['El precio original de compra sin ajuste','El de un modelo similar en condiciones comparables de uso y antigüedad','El mayor precio publicado en Internet','El valor sentimental declarado por el asegurado'],1,'El material usa como referencia un modelo similar en condiciones comparables de uso y antigüedad.'],

['Incendio','¿Cuál de estas situaciones se vincula mejor con un daño indirecto cubierto por Incendio?',['La pérdida de clientela futura sin cobertura adicional','El daño razonablemente causado al demoler parte de una pared para combatir el fuego','Una multa por falta de matafuegos','La caída de ventas meses después sin daño material'],1,'El material contempla daños derivados de medidas razonables de extinción, salvamento o demolición vinculadas al incendio.'],
['Incendio','¿Cuál es la diferencia conceptual más correcta entre fuego y explosión según el módulo?',['No existe diferencia técnica','La explosión es una combustión cuya reacción se presenta de manera instantánea o extremadamente rápida','El fuego siempre es físico y la explosión siempre química','La explosión solo puede producirse por gas'],1,'El módulo explica que la explosión se vincula con una reacción de combustión de velocidad instantánea y puede ser de origen químico o físico.'],
['Incendio','Una cobertura a prorrata presenta infraseguro del 25%. Frente a un daño de $400.000, sin franquicia, ¿qué principio se aplica?',['Se indemniza el 75% del daño','$400.000 siempre, porque el daño es menor a la suma asegurada','Se indemniza solo el 25% del daño','El siniestro queda sin cobertura'],0,'Si la suma asegurada representa el 75% del valor asegurable, la regla proporcional lleva a indemnizar el 75% del daño.'],
['Incendio','La cláusula de Reposición a Nuevo:',['Opera automáticamente en todo seguro de Incendio','Debe encontrarse pactada para desplazar el criterio de valor real con depreciación','Solo puede aplicarse a mercaderías','Equivale a una cobertura a Primer Riesgo Absoluto'],1,'La reposición a nuevo requiere pacto específico; no es la regla automática de todo seguro de Incendio.'],

['Seguro Técnico','En Equipos de Contratistas, ¿qué diferencia central marca el material frente a Rotura de Maquinarias?',['Equipos de Contratistas cubre daño accidental externo y excluye avería interna','Rotura de Maquinarias solo cubre robo','Equipos de Contratistas no cubre equipos en funcionamiento','Rotura de Maquinarias se limita a equipos móviles en tránsito'],0,'El módulo señala expresamente que Equipos de Contratistas cubre daño accidental externo y excluye avería interna.'],
['Seguro Técnico','En la combinación “Daños Totales Únicamente” para Equipos de Contratistas, el material asimila a pérdida total cuando la reparación es:',['Igual o superior al 50% del valor de la maquinaria','Igual o superior al 66%','Igual o superior al 80%','Superior al 100% exclusivamente'],2,'El material utiliza el 80% del valor de la maquinaria como umbral para asimilar la pérdida a total en esa combinación.'],
['Seguro Técnico','En Rotura de Maquinarias, la suma asegurada debe contemplar:',['Valor fiscal neto de amortizaciones exclusivamente','Valor de reposición a nuevo, incluyendo transporte, montaje y aduana cuando corresponda','Valor de venta usado sin flete ni montaje','Solo el precio original de factura'],1,'El módulo fija como base el valor de reposición a nuevo incluyendo los costos asociados indicados.'],
['Seguro Técnico','En Todo Riesgo Montaje, la medida de la prestación indicada por el material es:',['Primer Riesgo Absoluto','A prorrata','Valor tasado obligatorio','Primer Riesgo Relativo exclusivamente'],1,'El resumen del módulo de Todo Riesgo Montaje señala medida de prestación a prorrata.'],

['Todo Riesgo Operativo','¿Qué rasgo distingue estructuralmente al Todo Riesgo Operativo?',['Es una póliza de riesgos nominados donde solo se cubre lo expresamente mencionado','Es una póliza de riesgos innominados definida principalmente por sus exclusiones','Solo cubre bienes inmuebles','Obliga siempre a contratar Daños Materiales y Pérdida de Beneficios conjuntamente'],1,'El TRO es presentado como seguro de riesgos innominados definido por exclusiones.'],
['Todo Riesgo Operativo','En TRO, para rechazar un siniestro por una exclusión, el material destaca que:',['El asegurado debe probar que la exclusión no existe','Opera una inversión de la carga de la prueba y el asegurador debe acreditar la exclusión','El PAS debe probar la causa del daño','La exclusión se presume siempre'],1,'El módulo señala expresamente la inversión de la carga de la prueba respecto de las exclusiones.'],
['Todo Riesgo Operativo','La Sección II de Pérdida de Beneficios se activa, en términos generales, cuando la interrupción del negocio deriva de:',['Cualquier caída de ventas, aun sin daño material','Un hecho amparado bajo la cobertura de Daños Materiales','Una decisión comercial del asegurado','Una variación del tipo de cambio'],1,'La Sección II cubre la interrupción consecuencia de un hecho amparado bajo Daños Materiales.'],
['Todo Riesgo Operativo','¿Qué es el Período de Espera o Deducible en Pérdida de Beneficios?',['El tiempo máximo durante el cual puede durar la póliza','La cantidad de días a cargo del asegurado desde el inicio del Período de Indemnización','El plazo para denunciar el siniestro','Los doce meses anteriores al siniestro'],1,'El material lo define como el número de días a cargo del asegurado desde el comienzo del período de indemnización.'],

['Transporte','En transporte terrestre, ¿cuándo es posible el abandono del vehículo conforme al art. 124 estudiado?',['Ante cualquier daño parcial superior al 50%','Solo si existe pérdida total efectiva','Cuando la reparación supera el 80%','Siempre que el asegurado lo comunique dentro de 30 días'],1,'La Ley 17.418 dispone que, tratándose de vehículos de transporte terrestre, el abandono solo es posible si existe pérdida total efectiva.'],
['Transporte','Una mercadería transportada en vehículo propio sufre hurto. ¿Qué matiz señala el módulo respecto de la cobertura adicional de Hurto y Falta de Entrega?',['Puede contratarse indistintamente para vehículo propio o de terceros','Se prevé para mercadería transportada por terceros, no para bienes transportados por el propio dueño en vehículo propio','Solo se cubre si el hurto ocurre durante carga o descarga','Solo se cubre si existe violencia'],1,'El módulo limita esa cobertura adicional a mercaderías transportadas por terceros, donde puede existir responsabilidad contractual del transportista.'],
['Transporte','En la cobertura adicional de Daños a mercaderías, ¿cuál de estas causas aparece expresamente excluida?',['Rotura por causa física externa','Mojadura accidental externa','Vicio propio o naturaleza inherente del bien','Abolladura durante el transporte'],2,'El módulo cubre daños físicos externos pero excluye, entre otros, demora, vicio propio y naturaleza inherente.'],
['Transporte','La cobertura de Estadía en Aduana se vincula principalmente con:',['Mercadería exportada después de salir del país','Mercadería importada mientras permanece en zona primaria aduanera hasta su destino definitivo para despacho','Vehículos de transporte detenidos por infracciones','Únicamente equipaje de pasajeros'],1,'El material la presenta como extensión para mercadería importada durante su permanencia en zona primaria aduanera.'],

['Aeronavegación','Una aeronave desaparece y no se tienen noticias durante tres meses. Según el material:',['Nunca puede considerarse pérdida total sin hallazgo de restos','Puede considerarse pérdida total','Solo existe pérdida parcial constructiva','La cobertura se suspende hasta que transcurra un año'],1,'El módulo contempla la desaparición durante tres meses como supuesto de pérdida total.'],
['Aeronavegación','En casco aeronáutico, un daño cuyo costo supera el 85% del valor de la aeronave es tratado como:',['Daño parcial en todos los casos','Pérdida total según el criterio del material','Pérdida de beneficios','Franquicia agravada'],1,'El material fija el 85% como criterio de pérdida total para el casco aeronáutico estudiado.'],
['Aeronavegación','¿Cuál de estas circunstancias aparece entre las exclusiones de casco aeronáutico?',['Aeronave sin certificado de aeronavegabilidad','Robo total de la aeronave en todos los casos','Daños en tierra dentro del hangar','Impacto accidental no excluido'],0,'El módulo enumera la falta de certificado de aeronavegabilidad entre las exclusiones.'],
['Aeronavegación','La pérdida total constructiva se configura, según el resumen del módulo, cuando:',['Los daños superan el 50% del valor','Los gastos de reparación superan el valor asegurado','La aeronave permanece inmovilizada 30 días','El piloto pierde su licencia después del siniestro'],1,'El material distingue pérdida total constructiva cuando los gastos de reparación superan el valor asegurado.'],

['Ética y Fraude','Un PAS exagera deliberadamente daños en la denuncia de un cliente para aumentar la indemnización. ¿Cómo debe analizarse?',['Como una técnica de negociación admitida','Como participación en una maniobra fraudulenta','Como reticencia no dolosa','Como simple error de liquidación'],1,'El fraude incluye simular o exagerar ilícitamente las consecuencias de un siniestro para obtener un beneficio indebido.'],
['Ética y Fraude','¿Cuál de estas situaciones NO constituye por sí sola fraude según el material?',['Simular un siniestro inexistente','Provocar intencionalmente el siniestro','Que exista una diferencia significativa entre lo reclamado y lo que finalmente determina la liquidación','Exagerar conscientemente el daño para enriquecerse'],2,'El módulo aclara que una diferencia entre lo reclamado y lo liquidado no constituye por sí sola fraude.'],
['Ética y Fraude','Un rechazo de siniestro por aplicación de una exclusión contractual:',['Constituye automáticamente fraude con seguros','No constituye fraude por ese solo hecho','Siempre implica lavado de activos','Solo es válido si interviene la UIF'],1,'El material aclara que el rechazo por simple aplicación de una cláusula de exclusión no constituye fraude por sí mismo.'],
['Ética y Fraude','¿Qué elemento es esencial para hablar de fraude?',['Un error material involuntario','Engaño consciente orientado a obtener un provecho indebido','Una demora administrativa','Un desacuerdo sobre la valuación'],1,'El fraude supone engaño o inexactitud consciente con intención de obtener un beneficio indebido.'],

['Cultura de Prevención','¿Cuál es la función del PAS dentro de la cultura de prevención según el material?',['Limitarse a vender la póliza solicitada','Detectar riesgos, asesorar, transmitir medidas preventivas y posicionarse como administrador de riesgos','Sustituir al inspector de la SSN','Evitar hablar de prevención para no asumir responsabilidades'],1,'El módulo asigna al PAS un papel activo en detectar riesgos, asesorar y generar cultura preventiva.'],
['Cultura de Prevención','“Vender con la verdad” aparece en el material asociado a:',['Una técnica contable','El papel del PAS en la generación de cultura de prevención','La liquidación de siniestros','La regulación de inversiones'],1,'El módulo lo incluye entre las acciones concretas del PAS dentro de la cultura de prevención.'],
['Cultura de Prevención','¿Qué conducta agrega valor al asesoramiento del PAS según el módulo?',['Evitar inspecciones para reducir costos','Acompañar la identificación y prevención de riesgos además de explicar coberturas y sumas','Ofrecer siempre la póliza de menor prima','Omitir exclusiones complejas'],1,'El material destaca el asesoramiento preventivo y claro como valor agregado del PAS.'],
['Cultura de Prevención','El concepto de prevención, en el enfoque del módulo, debería:',['Aplicarse solo después de un siniestro','Integrarse en la actividad diaria como un estilo de actuación','Delegarse completamente a la aseguradora','Limitarse a riesgos laborales'],1,'El módulo propone integrar la prevención a la actividad diaria y al asesoramiento profesional.'],

['Integrales','En un Integral de Colegios, ¿qué cobertura resulta especialmente vinculada a la obligación legal del establecimiento educativo?',['Responsabilidad Civil Escolar','Seguro de Caución','Transporte Marítimo','Robo de Valores en Tránsito'],0,'El material destaca la obligación de cubrir la responsabilidad del establecimiento educativo mediante un seguro de RC específico.'],
['Integrales','¿Cuál de estas coberturas es característica de un Integral de Hoteles por la presencia de bienes de pasajeros?',['Robo de bienes de huéspedes','Seguro de vida individual del dueño','Caución aduanera','Casco marítimo'],0,'El módulo incorpora coberturas específicas para bienes y valores de huéspedes.'],
['Integrales','En un Integral de Hoteles, la guarda de vehículos aparece como:',['Una cobertura específica que suele contemplarse, generalmente a título no oneroso','Una exclusión absoluta de cualquier integral','Una prestación propia de ART','Una cobertura obligatoria sin condiciones'],0,'El material la enumera entre coberturas específicas del riesgo hotelero, generalmente a título no oneroso.'],
['Integrales','Un hotel organiza rafting para huéspedes. Según las exclusiones específicas estudiadas:',['Es una actividad de bajo riesgo incluida automáticamente','Puede quedar alcanzada por exclusiones de deportes o actividades de alto riesgo','Solo se excluye si ocurre fuera del hotel','Se cubre por Cristales'],1,'El módulo enumera actividades como rafting, alpinismo, escalada y otras de alto riesgo entre las exclusiones específicas.']
];